"""
Answer Generator Module
=========================
Part 2 of the SEAL Loop: Attempt Answers

This module uses the language model to generate answers to the
self-generated questions. These answers are then evaluated by
the Evaluator module to produce training signals.

Data Flow:
  Question + Topic Context
    → Answer Prompt Construction
    → LLM Generation (with current model weights)
    → Answer Extraction
    → (Question, Answer) Pair

Key Design Decision:
  The answer is generated by the SAME model that will be updated.
  This creates a self-improvement signal: the model learns from
  its own mistakes, gradually improving its DSA knowledge.
"""

import logging
from typing import List, Dict, Optional, Tuple
from dataclasses import dataclass

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

from seal_dsa.config import SEALDSAConfig
from seal_dsa.modules.question_generator import GeneratedQuestion

logger = logging.getLogger(__name__)


@dataclass
class GeneratedAnswer:
    """Represents a generated answer paired with its question."""
    question: GeneratedQuestion
    answer: str
    confidence: float  # Self-assessed confidence (0-1)
    generation_tokens: int  # Number of tokens generated


# ── Prompt Templates ────────────────────────────────────────────

ANSWER_PROMPT_TEMPLATE = """You are a computer science student answering a Data Structures and Algorithms question.

Topic: {topic}
Difficulty: {difficulty}

Question: {question}

Provide a detailed, step-by-step answer. Include:
1. The approach/algorithm
2. Time and space complexity analysis
3. Edge cases to consider
{code_instruction}

Answer:"""

CODE_INSTRUCTION = """4. Python code implementation if applicable"""
NO_CODE_INSTRUCTION = ""


ANSWER_WITH_REASONING_PROMPT = """You are solving a DSA problem step by step.

Question: {question}

Think through this problem:
1. Understand: What is being asked?
2. Plan: What approach should I use?
3. Solve: Work through the solution
4. Verify: Check edge cases and complexity

Solution:"""


REFINEMENT_PROMPT = """You previously answered this DSA question, but your answer had issues.

Question: {question}

Previous attempt issues: {feedback}

Please provide an improved answer that addresses these issues. Include:
1. Corrected approach / algorithm
2. Time and space complexity analysis
3. Working Python code implementation
4. Edge case handling

Improved Solution:"""


class AnswerGenerator:
    """
    Generates answers to DSA questions using the language model.
    
    This is the second step in the SEAL loop. The same model that
    generated the questions now attempts to answer them. The quality
    of these answers determines the training signal.
    
    Architecture:
    ┌─────────────────────────────────────────┐
    │         Answer Generator                │
    │                                         │
    │  Question + Context                     │
    │        │                                │
    │        ▼                                │
    │  ┌──────────────┐                       │
    │  │ Prompt        │                      │
    │  │ Construction  │ ← Topic context      │
    │  └──────┬───────┘                       │
    │         ▼                               │
    │  ┌──────────────┐                       │
    │  │ LLM          │ ← Temperature=0.3     │
    │  │ Generation   │ ← Deterministic mode  │
    │  └──────┬───────┘                       │
    │         ▼                               │
    │  ┌──────────────┐                       │
    │  │ Answer        │                      │
    │  │ Extraction   │                       │
    │  └──────┬───────┘                       │
    │         ▼                               │
    │  (Question, Answer) Pair                │
    └─────────────────────────────────────────┘
    """
    
    def __init__(
        self,
        model: AutoModelForCausalLM,
        tokenizer: AutoTokenizer,
        config: SEALDSAConfig,
    ):
        self.model = model
        self.tokenizer = tokenizer
        self.config = config
        self.answers_generated = 0
    
    @torch.no_grad()
    def generate_answer(
        self,
        question: GeneratedQuestion,
        use_reasoning: bool = True,
    ) -> GeneratedAnswer:
        """
        Generate an answer for a single question.
        
        Args:
            question: The GeneratedQuestion to answer
            use_reasoning: Whether to use chain-of-thought prompting
            
        Returns:
            GeneratedAnswer with the model's response
        """
        if use_reasoning:
            system_msg = "You are solving a DSA problem step by step."
            user_msg = (
                f"Question: {question.question}\n\n"
                f"Think through this problem:\n"
                f"1. Understand: What is being asked?\n"
                f"2. Plan: What approach should I use?\n"
                f"3. Solve: Work through the solution\n"
                f"4. Verify: Check edge cases and complexity"
            )
        else:
            code_inst = "\n4. Python code implementation if applicable" if question.question_type == "coding" else ""
            system_msg = "You are a computer science student answering a Data Structures and Algorithms question."
            user_msg = (
                f"Topic: {question.topic}\n"
                f"Difficulty: {question.difficulty}\n\n"
                f"Question: {question.question}\n\n"
                f"Provide a detailed, step-by-step answer. Include:\n"
                f"1. The approach/algorithm\n"
                f"2. Time and space complexity analysis\n"
                f"3. Edge cases to consider{code_inst}"
            )
        
        messages = [
            {"role": "system", "content": system_msg},
            {"role": "user", "content": user_msg},
        ]
        prompt = self.tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )
        
        try:
            inputs = self.tokenizer(
                prompt,
                return_tensors="pt",
                truncation=True,
                max_length=self.config.model.max_length,
            ).to(self.model.device)
            
            outputs = self.model.generate(
                **inputs,
                max_new_tokens=512,
                temperature=0.3,  # Lower temperature for more focused answers
                top_p=0.9,
                do_sample=True,
                pad_token_id=self.tokenizer.pad_token_id,
                repetition_penalty=1.1,
                output_scores=True,
                return_dict_in_generate=True,
            )
            
            # Extract only generated tokens
            generated_ids = outputs.sequences[0][inputs['input_ids'].shape[1]:]
            answer_text = self.tokenizer.decode(
                generated_ids, skip_special_tokens=True
            ).strip()
            
            # Bug 11 fix: Compute confidence from generation scores directly
            # instead of running a redundant full forward pass
            confidence = self._estimate_confidence_from_scores(outputs.scores)
            
            self.answers_generated += 1
            
            return GeneratedAnswer(
                question=question,
                answer=answer_text,
                confidence=confidence,
                generation_tokens=len(generated_ids),
            )
            
        except Exception as e:
            logger.error(f"Answer generation failed: {e}")
            return GeneratedAnswer(
                question=question,
                answer="[Generation Failed]",
                confidence=0.0,
                generation_tokens=0,
            )
    
    def generate_answers_batch(
        self,
        questions: List[GeneratedQuestion],
    ) -> List[GeneratedAnswer]:
        """
        Generate answers for a batch of questions.
        
        Processes questions sequentially (due to memory constraints
        on Colab Free Tier), but can be extended for parallel
        generation on larger GPUs.
        
        Args:
            questions: List of questions to answer
            
        Returns:
            List of GeneratedAnswer objects
        """
        answers = []
        
        for i, question in enumerate(questions):
            logger.debug(f"Answering question {i+1}/{len(questions)}")
            answer = self.generate_answer(question)
            answers.append(answer)
            
            # Memory management for Colab
            if i % 10 == 0 and torch.cuda.is_available():
                torch.cuda.empty_cache()
        
        logger.info(f"Generated {len(answers)} answers")
        return answers
    
    def _estimate_confidence_from_scores(
        self,
        scores: tuple,
    ) -> float:
        """
        Estimate model confidence from generation logit scores.
        
        Bug 11 fix: Uses scores returned by generate(output_scores=True)
        directly, avoiding an expensive redundant forward pass through
        the entire model.
        
        Returns:
            float in [0, 1] — mean token probability.
        """
        try:
            if not scores or len(scores) == 0:
                return 0.3
            
            # Each element in scores is (1, vocab_size) logits
            # Take the max probability at each step as confidence signal
            total_prob = 0.0
            for step_logits in scores:
                probs = torch.softmax(step_logits[0], dim=-1)
                max_prob = probs.max().item()
                total_prob += max_prob
            
            confidence = total_prob / len(scores)
            return max(0.0, min(1.0, confidence))
            
        except Exception as e:
            logger.debug(f"Confidence estimation failed: {e}")
            return 0.3
    
    @torch.no_grad()
    def generate_refined_answer(
        self,
        question: GeneratedQuestion,
        previous_answer: str,
        feedback: str,
    ) -> GeneratedAnswer:
        """
        Generate a refined answer using feedback from the evaluator.
        
        This implements the self-refinement step: when an answer scores
        poorly, the model is given its own feedback and asked to improve.
        
        Args:
            question: The original question
            previous_answer: The model's initial (poor) attempt
            feedback: Evaluator feedback on what was wrong
            
        Returns:
            A new GeneratedAnswer with the refined response.
        """
        messages = [
            {"role": "system", "content": "You are improving a previously incorrect DSA answer."},
            {"role": "user", "content": (
                f"You previously answered this DSA question, but your answer had issues.\n\n"
                f"Question: {question.question}\n\n"
                f"Previous attempt issues: {feedback}\n\n"
                f"Please provide an improved answer that addresses these issues. Include:\n"
                f"1. Corrected approach / algorithm\n"
                f"2. Time and space complexity analysis\n"
                f"3. Working Python code implementation\n"
                f"4. Edge case handling"
            )},
        ]
        prompt = self.tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )
        
        try:
            inputs = self.tokenizer(
                prompt,
                return_tensors="pt",
                truncation=True,
                max_length=self.config.model.max_length,
            ).to(self.model.device)
            
            outputs = self.model.generate(
                **inputs,
                max_new_tokens=512,
                temperature=0.4,  # Slightly higher than normal for creativity
                top_p=0.9,
                do_sample=True,
                pad_token_id=self.tokenizer.pad_token_id,
                repetition_penalty=1.15,  # Stronger to avoid repeating mistakes
                output_scores=True,
                return_dict_in_generate=True,
            )
            
            generated_ids = outputs.sequences[0][inputs['input_ids'].shape[1]:]
            answer_text = self.tokenizer.decode(
                generated_ids, skip_special_tokens=True
            ).strip()
            
            confidence = self._estimate_confidence_from_scores(outputs.scores)
            self.answers_generated += 1
            
            return GeneratedAnswer(
                question=question,
                answer=answer_text,
                confidence=confidence,
                generation_tokens=len(generated_ids),
            )
            
        except Exception as e:
            logger.error(f"Refinement generation failed: {e}")
            return GeneratedAnswer(
                question=question,
                answer=previous_answer,  # Keep original if refinement fails
                confidence=0.0,
                generation_tokens=0,
            )
    
    def get_training_pairs(
        self,
        answers: List[GeneratedAnswer],
    ) -> List[Dict[str, str]]:
        """
        Convert answers to training pair format.
        
        Returns pairs in the format expected by the Parameter Updater:
        [
            {
                "input": "<question>",
                "output": "<answer>",
                "topic": "<topic>",
                "score": <evaluation_score>,  # Added by evaluator
            },
            ...
        ]
        """
        pairs = []
        for ans in answers:
            pairs.append({
                "input": ans.question.question,
                "output": ans.answer,
                "topic": ans.question.topic,
                "difficulty": ans.question.difficulty,
                "confidence": ans.confidence,
            })
        return pairs
    
    def get_stats(self) -> Dict:
        """Return generation statistics."""
        return {
            "total_answers_generated": self.answers_generated,
        }
