"""
Answer Generator Module
=========================
Part 2 of the SEAL Loop: Attempt Answers

This module uses the language model to generate answers to the
self-generated questions. These answers are then evaluated by
the Evaluator module to produce training signals.

Data Flow:
  Question + Topic Context
    → Answer Prompt Construction
    → LLM Generation (with current model weights)
    → Answer Extraction
    → (Question, Answer) Pair

Key Design Decision:
  The answer is generated by the SAME model that will be updated.
  This creates a self-improvement signal: the model learns from
  its own mistakes, gradually improving its DSA knowledge.
"""

import logging
from typing import List, Dict, Optional, Tuple
from dataclasses import dataclass

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

from seal_dsa.config import SEALDSAConfig
from seal_dsa.modules.question_generator import GeneratedQuestion

logger = logging.getLogger(__name__)


@dataclass
class GeneratedAnswer:
    """Represents a generated answer paired with its question."""
    question: GeneratedQuestion
    answer: str
    confidence: float  # Self-assessed confidence (0-1)
    generation_tokens: int  # Number of tokens generated


# ── Prompt Templates ────────────────────────────────────────────

ANSWER_PROMPT_TEMPLATE = """You are a computer science student answering a Data Structures and Algorithms question.

Topic: {topic}
Difficulty: {difficulty}

Question: {question}

Provide a detailed, step-by-step answer. Include:
1. The approach/algorithm
2. Time and space complexity analysis
3. Edge cases to consider
{code_instruction}

Answer:"""

CODE_INSTRUCTION = """4. Python code implementation if applicable"""
NO_CODE_INSTRUCTION = ""


ANSWER_WITH_REASONING_PROMPT = """You are solving a DSA problem step by step.

Question: {question}

Think through this problem:
1. Understand: What is being asked?
2. Plan: What approach should I use?
3. Solve: Work through the solution
4. Verify: Check edge cases and complexity

Solution:"""


REFINEMENT_PROMPT = """You previously answered this DSA question, but your answer had issues.

Question: {question}

Previous attempt issues: {feedback}

Please provide an improved answer that addresses these issues. Include:
1. Corrected approach / algorithm
2. Time and space complexity analysis
3. Working Python code implementation
4. Edge case handling

Improved Solution:"""


class AnswerGenerator:
    """
    Generates answers to DSA questions using the language model.
    
    This is the second step in the SEAL loop. The same model that
    generated the questions now attempts to answer them. The quality
    of these answers determines the training signal.
    
    Architecture:
    ┌─────────────────────────────────────────┐
    │         Answer Generator                │
    │                                         │
    │  Question + Context                     │
    │        │                                │
    │        ▼                                │
    │  ┌──────────────┐                       │
    │  │ Prompt        │                      │
    │  │ Construction  │ ← Topic context      │
    │  └──────┬───────┘                       │
    │         ▼                               │
    │  ┌──────────────┐                       │
    │  │ LLM          │ ← Temperature=0.3     │
    │  │ Generation   │ ← Deterministic mode  │
    │  └──────┬───────┘                       │
    │         ▼                               │
    │  ┌──────────────┐                       │
    │  │ Answer        │                      │
    │  │ Extraction   │                       │
    │  └──────┬───────┘                       │
    │         ▼                               │
    │  (Question, Answer) Pair                │
    └─────────────────────────────────────────┘
    """
    
    def __init__(
        self,
        model: AutoModelForCausalLM,
        tokenizer: AutoTokenizer,
        config: SEALDSAConfig,
    ):
        self.model = model
        self.tokenizer = tokenizer
        self.config = config
        self.answers_generated = 0
    
    @torch.no_grad()
    def generate_answer(
        self,
        question: GeneratedQuestion,
        use_reasoning: bool = True,
    ) -> GeneratedAnswer:
        """
        Generate an answer for a single question.
        
        Args:
            question: The GeneratedQuestion to answer
            use_reasoning: Whether to use chain-of-thought prompting
            
        Returns:
            GeneratedAnswer with the model's response
        """
        if use_reasoning:
            prompt = ANSWER_WITH_REASONING_PROMPT.format(
                question=question.question,
            )
        else:
            code_inst = CODE_INSTRUCTION if question.question_type == "coding" else NO_CODE_INSTRUCTION
            prompt = ANSWER_PROMPT_TEMPLATE.format(
                topic=question.topic,
                difficulty=question.difficulty,
                question=question.question,
                code_instruction=code_inst,
            )
        
        try:
            inputs = self.tokenizer(
                prompt,
                return_tensors="pt",
                truncation=True,
                max_length=self.config.model.max_length,
            ).to(self.model.device)
            
            outputs = self.model.generate(
                **inputs,
                max_new_tokens=512,
                temperature=0.3,  # Lower temperature for more focused answers
                top_p=0.9,
                do_sample=True,
                pad_token_id=self.tokenizer.pad_token_id,
                repetition_penalty=1.1,
            )
            
            # Extract only generated tokens
            generated_ids = outputs[0][inputs['input_ids'].shape[1]:]
            answer_text = self.tokenizer.decode(
                generated_ids, skip_special_tokens=True
            ).strip()
            
            # Compute rough confidence based on generation probability
            confidence = self._estimate_confidence(outputs, inputs)
            
            self.answers_generated += 1
            
            return GeneratedAnswer(
                question=question,
                answer=answer_text,
                confidence=confidence,
                generation_tokens=len(generated_ids),
            )
            
        except Exception as e:
            logger.error(f"Answer generation failed: {e}")
            return GeneratedAnswer(
                question=question,
                answer="[Generation Failed]",
                confidence=0.0,
                generation_tokens=0,
            )
    
    def generate_answers_batch(
        self,
        questions: List[GeneratedQuestion],
    ) -> List[GeneratedAnswer]:
        """
        Generate answers for a batch of questions.
        
        Processes questions sequentially (due to memory constraints
        on Colab Free Tier), but can be extended for parallel
        generation on larger GPUs.
        
        Args:
            questions: List of questions to answer
            
        Returns:
            List of GeneratedAnswer objects
        """
        answers = []
        
        for i, question in enumerate(questions):
            logger.debug(f"Answering question {i+1}/{len(questions)}")
            answer = self.generate_answer(question)
            answers.append(answer)
            
            # Memory management for Colab
            if i % 10 == 0 and torch.cuda.is_available():
                torch.cuda.empty_cache()
        
        logger.info(f"Generated {len(answers)} answers")
        return answers
    
    def _estimate_confidence(
        self,
        outputs: torch.Tensor,
        inputs: dict,
    ) -> float:
        """
        Estimate model confidence from generation log-probabilities.
        
        Computes the average token probability across the generated
        sequence using a forward pass. Higher average probability
        indicates the model is more "certain" about its answer.
        
        Returns:
            float in [0, 1] — mean token probability.
        """
        try:
            generated_ids = outputs[0]  # full sequence including prompt
            input_len = inputs['input_ids'].shape[1]
            gen_len = generated_ids.shape[0] - input_len
            
            if gen_len <= 0:
                return 0.1
            
            # Forward pass to get logits
            with torch.no_grad():
                model_out = self.model(generated_ids.unsqueeze(0))
                logits = model_out.logits  # (1, seq_len, vocab_size)
            
            # Only look at generated token positions
            # Shift: logit at position t predicts token at position t+1
            gen_logits = logits[0, input_len - 1:-1, :]  # (gen_len, vocab)
            gen_tokens = generated_ids[input_len:]         # (gen_len,)
            
            # Compute per-token probability
            probs = torch.softmax(gen_logits, dim=-1)
            token_probs = probs.gather(
                -1, gen_tokens.unsqueeze(-1)
            ).squeeze(-1)  # (gen_len,)
            
            # Mean probability as confidence
            confidence = token_probs.mean().item()
            return max(0.0, min(1.0, confidence))
            
        except Exception as e:
            logger.debug(f"Confidence estimation failed: {e}")
            # Fallback: length-based heuristic
            generated_length = outputs.shape[1] - inputs['input_ids'].shape[1]
            if generated_length > 200:
                return 0.7
            elif generated_length > 100:
                return 0.5
            elif generated_length > 50:
                return 0.3
            else:
                return 0.2
    
    @torch.no_grad()
    def generate_refined_answer(
        self,
        question: GeneratedQuestion,
        previous_answer: str,
        feedback: str,
    ) -> GeneratedAnswer:
        """
        Generate a refined answer using feedback from the evaluator.
        
        This implements the self-refinement step: when an answer scores
        poorly, the model is given its own feedback and asked to improve.
        
        Args:
            question: The original question
            previous_answer: The model's initial (poor) attempt
            feedback: Evaluator feedback on what was wrong
            
        Returns:
            A new GeneratedAnswer with the refined response.
        """
        prompt = REFINEMENT_PROMPT.format(
            question=question.question,
            feedback=feedback,
        )
        
        try:
            inputs = self.tokenizer(
                prompt,
                return_tensors="pt",
                truncation=True,
                max_length=self.config.model.max_length,
            ).to(self.model.device)
            
            outputs = self.model.generate(
                **inputs,
                max_new_tokens=512,
                temperature=0.4,  # Slightly higher than normal for creativity
                top_p=0.9,
                do_sample=True,
                pad_token_id=self.tokenizer.pad_token_id,
                repetition_penalty=1.15,  # Stronger to avoid repeating mistakes
            )
            
            generated_ids = outputs[0][inputs['input_ids'].shape[1]:]
            answer_text = self.tokenizer.decode(
                generated_ids, skip_special_tokens=True
            ).strip()
            
            confidence = self._estimate_confidence(outputs, inputs)
            self.answers_generated += 1
            
            return GeneratedAnswer(
                question=question,
                answer=answer_text,
                confidence=confidence,
                generation_tokens=len(generated_ids),
            )
            
        except Exception as e:
            logger.error(f"Refinement generation failed: {e}")
            return GeneratedAnswer(
                question=question,
                answer=previous_answer,  # Keep original if refinement fails
                confidence=0.0,
                generation_tokens=0,
            )
    
    def get_training_pairs(
        self,
        answers: List[GeneratedAnswer],
    ) -> List[Dict[str, str]]:
        """
        Convert answers to training pair format.
        
        Returns pairs in the format expected by the Parameter Updater:
        [
            {
                "input": "<question>",
                "output": "<answer>",
                "topic": "<topic>",
                "score": <evaluation_score>,  # Added by evaluator
            },
            ...
        ]
        """
        pairs = []
        for ans in answers:
            pairs.append({
                "input": ans.question.question,
                "output": ans.answer,
                "topic": ans.question.topic,
                "difficulty": ans.question.difficulty,
                "confidence": ans.confidence,
            })
        return pairs
    
    def get_stats(self) -> Dict:
        """Return generation statistics."""
        return {
            "total_answers_generated": self.answers_generated,
        }
